"""Add jira chart config to test plans

Revision ID: 1a7689ec7f18
Revises: b2c3d4e5f6g7
Create Date: 2026-03-06 09:57:43.670597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a7689ec7f18'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.execute('DROP VIEW IF EXISTS team_hierarchy CASCADE')

    op.drop_index('idx_parent_team', table_name='automation_sub_teams')
    op.drop_table('automation_sub_teams')
    op.drop_table('automation_case_execute_result')
    op.drop_table('automation_scheduled_test_suite')
    
    op.drop_index('idx_team_name', table_name='automation_teams')
    op.drop_table('automation_teams')
    op.drop_table('automation_scheduled_jobs')
    op.drop_table('automation_test_run_result')
    op.drop_table('automation_configuration')
    op.drop_index('idx_automation_auth_email', table_name='automation_auth')
    op.drop_index('idx_automation_auth_google_id', table_name='automation_auth')
    op.drop_table('automation_auth')
    op.drop_table('automation_data')
    op.drop_table('automation_test_case')
    op.drop_index('idx_sessions_created_at', table_name='chat_sessions')
    op.drop_index('idx_sessions_updated_at', table_name='chat_sessions')
    op.drop_index('idx_sessions_user_id', table_name='chat_sessions')
    op.drop_index('idx_sessions_user_updated_desc', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('idx_messages_role', table_name='chat_messages')
    op.drop_index('idx_messages_session_id', table_name='chat_messages')
    op.drop_index('idx_messages_timestamp', table_name='chat_messages')
    op.drop_index('idx_messages_user_id', table_name='chat_messages')
    op.drop_index('idx_messages_user_session', table_name='chat_messages')
    op.drop_index('idx_messages_user_session_role', table_name='chat_messages')
    op.drop_index('idx_messages_user_session_time', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('automation_test_suite')
    op.add_column('tcms_test_plans', sa.Column('jira_chart_filter_id', sa.Integer(), nullable=True))
    op.add_column('tcms_test_plans', sa.Column('jira_chart_field', sa.String(), nullable=True))
    op.alter_column('tcms_test_plans', 'sa_docs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('tcms_test_plans', 'sd_docs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('tcms_test_plans', 'timeline',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('tcms_test_plans', 'jira_display_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_tcms_test_results_run_id', table_name='tcms_test_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tcms_test_results_run_id', 'tcms_test_results', ['run_id'], unique=False)
    op.alter_column('tcms_test_plans', 'jira_display_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tcms_test_plans', 'timeline',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tcms_test_plans', 'sd_docs',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tcms_test_plans', 'sa_docs',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('tcms_test_plans', 'jira_chart_field')
    op.drop_column('tcms_test_plans', 'jira_chart_filter_id')
    op.create_table('automation_test_suite',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('automation_test_suite_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cases', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_regression', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('team', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_daily', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('environment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('repeat', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('execute_machine', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owners', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('subteam', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('binding_jenkins_job', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('driver', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='automation_test_suite_pkey'),
    sa.UniqueConstraint('uuid', name='automation_test_suite_uuid_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('automation_teams',
    sa.Column('team_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('team_id', name='automation_teams_pkey')
    )
    op.create_index('idx_team_name', 'automation_teams', ['team_name'], unique=False)
    op.create_table('automation_sub_teams',
    sa.Column('sub_team_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sub_team_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_team_id'], ['automation_teams.team_id'], name='automation_sub_teams_parent_team_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sub_team_id', name='automation_sub_teams_pkey')
    )
    op.create_index('idx_parent_team', 'automation_sub_teams', ['parent_team_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False, comment='訊息唯一標識符 (UUID)'),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='所屬會話ID'),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='用戶唯一標識符'),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='訊息角色：user 或 assistant'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='訊息內容'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='訊息元數據（如處理路徑、時間等）'),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='訊息時間戳'),
    sa.CheckConstraint("role::text = ANY (ARRAY['user'::character varying, 'assistant'::character varying]::text[])", name='chat_messages_role_check'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], name='chat_messages_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_messages_pkey'),
    comment='聊天訊息表（支持用戶隔離）'
    )
    op.create_index('idx_messages_user_session_time', 'chat_messages', ['user_id', 'session_id', 'timestamp'], unique=False)
    op.create_index('idx_messages_user_session_role', 'chat_messages', ['user_id', 'session_id', 'role'], unique=False)
    op.create_index('idx_messages_user_session', 'chat_messages', ['user_id', 'session_id'], unique=False)
    op.create_index('idx_messages_user_id', 'chat_messages', ['user_id'], unique=False)
    op.create_index('idx_messages_timestamp', 'chat_messages', ['timestamp'], unique=False)
    op.create_index('idx_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_index('idx_messages_role', 'chat_messages', ['role'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='會話唯一標識符'),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='用戶唯一標識符'),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='會話標題'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='創建時間'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='最後更新時間'),
    sa.PrimaryKeyConstraint('session_id', name='chat_sessions_pkey'),
    comment='聊天會話表（支持用戶隔離）'
    )
    op.create_index('idx_sessions_user_updated_desc', 'chat_sessions', ['user_id', sa.text('updated_at DESC')], unique=False)
    op.create_index('idx_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_index('idx_sessions_updated_at', 'chat_sessions', [sa.text('updated_at DESC')], unique=False)
    op.create_index('idx_sessions_created_at', 'chat_sessions', ['created_at'], unique=False)
    op.create_table('automation_test_case',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('automation_test_case_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('test_steps', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), server_default=sa.text("'TW'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='automation_test_case_pkey'),
    sa.UniqueConstraint('case_id', name='automation_test_case_case_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('automation_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('environment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='automation_data_pkey')
    )
    op.create_table('automation_auth',
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Google OAuth user ID'),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='User email address from Google OAuth'),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='User display name from Google OAuth'),
    sa.Column('picture', sa.TEXT(), autoincrement=False, nullable=True, comment='User profile picture URL from Google OAuth'),
    sa.Column('login_type', sa.VARCHAR(length=50), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=True, comment='Login method: manual or google'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True, comment='Account creation timestamp'),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Last login timestamp'),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user', name='automation_auth_pkey'),
    sa.UniqueConstraint('google_id', name='automation_auth_google_id_key')
    )
    op.create_index('idx_automation_auth_google_id', 'automation_auth', ['google_id'], unique=False)
    op.create_index('idx_automation_auth_email', 'automation_auth', ['email'], unique=False)
    op.create_table('automation_case_execute_result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fail_function', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('terminal_output', sa.VARCHAR(length=15000), autoincrement=False, nullable=True),
    sa.Column('log_file_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('exc_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('build_version', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('case_result', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('test_run_uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['automation_test_case.case_id'], name='case_id'),
    sa.PrimaryKeyConstraint('id', name='automation_case_execute_result_pkey')
    )
    op.create_table('automation_configuration',
    sa.Column('config_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('config_value', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('config_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('valid', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='automation_configuration_pkey')
    )
    op.create_table('automation_test_run_result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('build_version', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pass', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fail', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('test_run_uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('is_regression', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('team', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_daily', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('test_suite_uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('request_uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='automation_test_run_result_pkey')
    )
    op.create_table('automation_scheduled_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('job_name', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('job_function', sa.CHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cron_expression', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_run_status', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timeout_seconds', sa.INTEGER(), server_default=sa.text('3600'), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='automation_scheduled_jobs_pkey')
    )
    op.create_table('automation_scheduled_test_suite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suite_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cron_expression', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('last_run', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_run', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_run_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('timeout_seconds', sa.INTEGER(), server_default=sa.text('3600'), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['automation_test_suite.uuid'], name='fk_suite'),
    sa.PrimaryKeyConstraint('id', name='automation_scheduled_test_suite_pkey')
    )

    # ### end Alembic commands ###
