"""Add jira chart config to test plans

Revision ID: 1a7689ec7f18
Revises: b2c3d4e5f6g7
Create Date: 2026-03-06 09:57:43.670597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a7689ec7f18'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.execute('DROP VIEW IF EXISTS team_hierarchy CASCADE')


    
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.execute("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name='tcms_test_plans' AND column_name='jira_chart_filter_id'
                ) THEN
                    ALTER TABLE tcms_test_plans ADD COLUMN jira_chart_filter_id INTEGER;
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name='tcms_test_plans' AND column_name='jira_chart_field'
                ) THEN
                    ALTER TABLE tcms_test_plans ADD COLUMN jira_chart_field VARCHAR;
                END IF;
            END $$;
        """)
    else:
        # For non-PostgreSQL (like SQLite in tests), add columns normally
        # SQLite doesn't strictly enforce DuplicateColumn in the same way, or you can use try/except.
        try:
            op.add_column('tcms_test_plans', sa.Column('jira_chart_filter_id', sa.Integer(), nullable=True))
            op.add_column('tcms_test_plans', sa.Column('jira_chart_field', sa.String(), nullable=True))
        except Exception:
            pass

    # SQLite has no `ALTER COLUMN TYPE`, and on SQLite the columns are already created
    # as JSON by the (now dialect-aware) `b2c3d4e5f6g7` migration, so the conversion is
    # a no-op there. Only run on PostgreSQL where JSONB → JSON is a real schema change.
    if bind.engine.name == 'postgresql':
        for col in ('sa_docs', 'sd_docs', 'timeline', 'jira_display_fields'):
            op.alter_column(
                'tcms_test_plans', col,
                existing_type=postgresql.JSONB(astext_type=sa.Text()),
                type_=sa.JSON(),
                existing_nullable=True,
            )
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.execute('DROP INDEX IF EXISTS ix_tcms_test_results_run_id')
    else:
        try:
            op.drop_index('ix_tcms_test_results_run_id', table_name='tcms_test_results')
        except Exception:
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass


    # ### end Alembic commands ###
