"""Add missing columns

Revision ID: 43b3c73328ee
Revises: 
Create Date: 2026-03-01 01:55:32.107542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b3c73328ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('test_cases', sa.Column('labels', sa.String(), nullable=True))
    # op.drop_constraint(None, 'test_plans', type_='foreignkey')
    # op.create_foreign_key(None, 'test_plans', 'test_plan_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.add_column('test_runs', sa.Column('assignee_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'test_runs', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_runs', type_='foreignkey')
    op.drop_column('test_runs', 'assignee_id')
    op.drop_constraint(None, 'test_plans', type_='foreignkey')
    op.create_foreign_key(None, 'test_plans', 'test_plan_folders', ['folder_id'], ['id'])
    op.drop_column('test_cases', 'labels')
    # ### end Alembic commands ###
