"""create_tcms_prefixed_tables

Revision ID: 8544e6486b06
Revises: 43b3c73328ee
Create Date: 2026-03-02 22:39:55.091952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8544e6486b06'
down_revision: Union[str, Sequence[str], None] = '43b3c73328ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tcms_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcms_projects_id'), 'tcms_projects', ['id'], unique=False)
    op.create_index(op.f('ix_tcms_projects_name'), 'tcms_projects', ['name'], unique=False)
    op.create_table('tcms_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('force_change_password', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcms_users_email'), 'tcms_users', ['email'], unique=True)
    op.create_index(op.f('ix_tcms_users_id'), 'tcms_users', ['id'], unique=False)
    op.create_index(op.f('ix_tcms_users_username'), 'tcms_users', ['username'], unique=True)
    op.create_table('tcms_test_plan_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tcms_test_plan_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['tcms_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcms_test_plan_folders_id'), 'tcms_test_plan_folders', ['id'], unique=False)
    op.create_table('tcms_test_run_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tcms_test_run_folders.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['tcms_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcms_test_run_folders_id'), 'tcms_test_run_folders', ['id'], unique=False)
    op.create_index(op.f('ix_tcms_test_run_folders_name'), 'tcms_test_run_folders', ['name'], unique=False)
    op.create_table('tcms_test_suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_suite_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('preconditions', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_suite_id'], ['tcms_test_suites.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['tcms_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcms_test_suites_id'), 'tcms_test_suites', ['id'], unique=False)
    op.create_index(op.f('ix_tcms_test_suites_name'), 'tcms_test_suites', ['name'], unique=False)
    op.create_table('tcms_test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('lifecycle_status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('layer', sa.String(), nullable=True),
    sa.Column('behavior', sa.String(), nullable=True),
    sa.Column('automation_status', sa.String(), nullable=True),
    sa.Column('is_flaky', sa.Boolean(), nullable=True),
    sa.Column('muted', sa.Boolean(), nullable=True),
    sa.Column('preconditions', sa.String(), nullable=True),
    sa.Column('postconditions', sa.String(), nullable=True),
    sa.Column('default_owner_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('labels', sa.String(), nullable=True),
    sa.Column('jira_keys', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['default_owner_id'], ['tcms_users.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['tcms_test_suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcms_test_cases_external_id'), 'tcms_test_cases', ['external_id'], unique=False)
    op.create_index(op.f('ix_tcms_test_cases_id'), 'tcms_test_cases', ['id'], unique=False)
    op.create_index(op.f('ix_tcms_test_cases_title'), 'tcms_test_cases', ['title'], unique=False)
    op.create_table('tcms_test_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['tcms_test_plan_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['tcms_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcms_test_plans_id'), 'tcms_test_plans', ['id'], unique=False)
    op.create_index(op.f('ix_tcms_test_plans_title'), 'tcms_test_plans', ['title'], unique=False)
    op.create_table('tcms_plan_cases',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['tcms_test_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['tcms_test_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', 'case_id')
    )
    op.create_table('tcms_test_cases_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('changed_fields', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['tcms_test_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tcms_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcms_test_cases_history_id'), 'tcms_test_cases_history', ['id'], unique=False)
    op.create_table('tcms_test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('test_plan_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['tcms_users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['tcms_test_run_folders.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['tcms_projects.id'], ),
    sa.ForeignKeyConstraint(['test_plan_id'], ['tcms_test_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcms_test_runs_id'), 'tcms_test_runs', ['id'], unique=False)
    op.create_index(op.f('ix_tcms_test_runs_title'), 'tcms_test_runs', ['title'], unique=False)
    op.create_table('tcms_test_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('expected_result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['tcms_test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcms_test_steps_id'), 'tcms_test_steps', ['id'], unique=False)
    op.create_table('tcms_plan_runs',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['tcms_test_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['tcms_test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', 'run_id')
    )
    op.create_table('tcms_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jira_bug_id', sa.String(), nullable=True),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['tcms_users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['tcms_test_cases.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['tcms_test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcms_test_results_id'), 'tcms_test_results', ['id'], unique=False)
    op.create_table('tcms_test_run_assignees',
    sa.Column('test_run_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_run_id'], ['tcms_test_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tcms_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_run_id', 'user_id')
    )
    op.create_table('tcms_test_step_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('test_step_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('actual_result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['test_result_id'], ['tcms_test_results.id'], ),
    sa.ForeignKeyConstraint(['test_step_id'], ['tcms_test_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcms_test_step_results_id'), 'tcms_test_step_results', ['id'], unique=False)
    # automation_* / chat_* tables are owned by qa-automation service — intentionally preserved
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='會話唯一標識符'),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='用戶唯一標識符'),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='會話標題'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='創建時間'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='最後更新時間'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('chat_sessions_pkey')),
    comment='聊天會話表（支持用戶隔離）'
    )
    op.create_index(op.f('idx_sessions_user_updated_desc'), 'chat_sessions', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_sessions_updated_at'), 'chat_sessions', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_sessions_created_at'), 'chat_sessions', ['created_at'], unique=False)
    op.create_table('automation_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('environment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_data_pkey'))
    )
    op.create_table('automation_test_suite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cases', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_regression', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('team', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_daily', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('environment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('repeat', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('execute_machine', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owners', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('subteam', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('binding_jenkins_job', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('driver', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_test_suite_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('automation_test_suite_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False, comment='訊息唯一標識符 (UUID)'),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='所屬會話ID'),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='用戶唯一標識符'),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='訊息角色：user 或 assistant'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='訊息內容'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='訊息元數據（如處理路徑、時間等）'),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='訊息時間戳'),
    sa.CheckConstraint("role::text = ANY (ARRAY['user'::character varying, 'assistant'::character varying]::text[])", name=op.f('chat_messages_role_check')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], name=op.f('chat_messages_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey')),
    comment='聊天訊息表（支持用戶隔離）'
    )
    op.create_index(op.f('idx_messages_user_session_time'), 'chat_messages', ['user_id', 'session_id', 'timestamp'], unique=False)
    op.create_index(op.f('idx_messages_user_session_role'), 'chat_messages', ['user_id', 'session_id', 'role'], unique=False)
    op.create_index(op.f('idx_messages_user_session'), 'chat_messages', ['user_id', 'session_id'], unique=False)
    op.create_index(op.f('idx_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_index(op.f('idx_messages_timestamp'), 'chat_messages', ['timestamp'], unique=False)
    op.create_index(op.f('idx_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('idx_messages_role'), 'chat_messages', ['role'], unique=False)
    op.create_table('automation_configuration',
    sa.Column('config_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('config_value', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('config_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('valid', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_configuration_pkey'))
    )
    op.create_table('automation_teams',
    sa.Column('team_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('team_id', name=op.f('automation_teams_pkey'))
    )
    op.create_index(op.f('idx_team_name'), 'automation_teams', ['team_name'], unique=False)
    op.create_table('automation_sub_teams',
    sa.Column('sub_team_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sub_team_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_team_id'], ['automation_teams.team_id'], name=op.f('automation_sub_teams_parent_team_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sub_team_id', name=op.f('automation_sub_teams_pkey'))
    )
    op.create_index(op.f('idx_parent_team'), 'automation_sub_teams', ['parent_team_id'], unique=False)
    op.create_table('automation_auth',
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Google OAuth user ID'),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='User email address from Google OAuth'),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='User display name from Google OAuth'),
    sa.Column('picture', sa.TEXT(), autoincrement=False, nullable=True, comment='User profile picture URL from Google OAuth'),
    sa.Column('login_type', sa.VARCHAR(length=50), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=True, comment='Login method: manual or google'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True, comment='Account creation timestamp'),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Last login timestamp'),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user', name=op.f('automation_auth_pkey')),
    sa.UniqueConstraint('google_id', name=op.f('automation_auth_google_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_automation_auth_google_id'), 'automation_auth', ['google_id'], unique=False)
    op.create_index(op.f('idx_automation_auth_email'), 'automation_auth', ['email'], unique=False)
    op.create_table('automation_case_execute_result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fail_function', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('terminal_output', sa.VARCHAR(length=15000), autoincrement=False, nullable=True),
    sa.Column('log_file_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('exc_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('build_version', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('case_result', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('test_run_uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['automation_test_case.case_id'], name=op.f('case_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_case_execute_result_pkey'))
    )
    op.create_table('automation_test_case',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('automation_test_case_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('test_steps', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), server_default=sa.text("'TW'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_test_case_pkey')),
    sa.UniqueConstraint('case_id', name=op.f('automation_test_case_case_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('automation_scheduled_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('job_name', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('job_function', sa.CHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cron_expression', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_run_status', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timeout_seconds', sa.INTEGER(), server_default=sa.text('3600'), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_scheduled_jobs_pkey'))
    )
    op.create_table('automation_test_run_result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('build_version', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pass', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fail', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('test_run_uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('is_regression', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('team', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_daily', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('test_suite_uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('request_uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_test_run_result_pkey'))
    )
    op.create_table('automation_scheduled_test_suite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suite_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cron_expression', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('last_run', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_run', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_run_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('timeout_seconds', sa.INTEGER(), server_default=sa.text('3600'), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['automation_test_suite.uuid'], name=op.f('fk_suite')),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_scheduled_test_suite_pkey'))
    )
    op.drop_index(op.f('ix_tcms_test_step_results_id'), table_name='tcms_test_step_results')
    op.drop_table('tcms_test_step_results')
    op.drop_table('tcms_test_run_assignees')
    op.drop_index(op.f('ix_tcms_test_results_id'), table_name='tcms_test_results')
    op.drop_table('tcms_test_results')
    op.drop_table('tcms_plan_runs')
    op.drop_index(op.f('ix_tcms_test_steps_id'), table_name='tcms_test_steps')
    op.drop_table('tcms_test_steps')
    op.drop_index(op.f('ix_tcms_test_runs_title'), table_name='tcms_test_runs')
    op.drop_index(op.f('ix_tcms_test_runs_id'), table_name='tcms_test_runs')
    op.drop_table('tcms_test_runs')
    op.drop_index(op.f('ix_tcms_test_cases_history_id'), table_name='tcms_test_cases_history')
    op.drop_table('tcms_test_cases_history')
    op.drop_table('tcms_plan_cases')
    op.drop_index(op.f('ix_tcms_test_plans_title'), table_name='tcms_test_plans')
    op.drop_index(op.f('ix_tcms_test_plans_id'), table_name='tcms_test_plans')
    op.drop_table('tcms_test_plans')
    op.drop_index(op.f('ix_tcms_test_cases_title'), table_name='tcms_test_cases')
    op.drop_index(op.f('ix_tcms_test_cases_id'), table_name='tcms_test_cases')
    op.drop_index(op.f('ix_tcms_test_cases_external_id'), table_name='tcms_test_cases')
    op.drop_table('tcms_test_cases')
    op.drop_index(op.f('ix_tcms_test_suites_name'), table_name='tcms_test_suites')
    op.drop_index(op.f('ix_tcms_test_suites_id'), table_name='tcms_test_suites')
    op.drop_table('tcms_test_suites')
    op.drop_index(op.f('ix_tcms_test_run_folders_name'), table_name='tcms_test_run_folders')
    op.drop_index(op.f('ix_tcms_test_run_folders_id'), table_name='tcms_test_run_folders')
    op.drop_table('tcms_test_run_folders')
    op.drop_index(op.f('ix_tcms_test_plan_folders_id'), table_name='tcms_test_plan_folders')
    op.drop_table('tcms_test_plan_folders')
    op.drop_index(op.f('ix_tcms_users_username'), table_name='tcms_users')
    op.drop_index(op.f('ix_tcms_users_id'), table_name='tcms_users')
    op.drop_index(op.f('ix_tcms_users_email'), table_name='tcms_users')
    op.drop_table('tcms_users')
    op.drop_index(op.f('ix_tcms_projects_name'), table_name='tcms_projects')
    op.drop_index(op.f('ix_tcms_projects_id'), table_name='tcms_projects')
    op.drop_table('tcms_projects')
    # ### end Alembic commands ###
